# dataset options
dataset: "WESAD"
dataset_dir: "/home/kavra/Datasets/physio/WESAD/"
type: "classification"
subject_agnostic: True
streams: ["ecg"]
gtruth: ""
low_data: 0.05
splits: 5
sr: 100
seed: 42

### model options
model_type: "s4"    # [resnet, s4]

# ResNet
in_channels: 1
base_filters: 64
kernel_size: 3
stride: 2
groups: 1
n_block: 10
n_classes: 256
projection_dim: 128
output_dim: 3

# S4
d_input: 1
d_output: 128
d_model: 128
n_layers: 6
dropout: 0.2

# training options
use_pretrained: 0
unfreeze: True
batch_size: 64
m_epochs: 200
optimizer: "Adam"
learning_rate: 0.0001
weight_decay: 0

val_freq: 1     # how often to validate (runs validation every val_freq epochs)
log_freq: 2     # how often to log (logs every log_freq steps)
workers: 4
n_cuda: "0"
bit_precision: 16
ckpt_path: null     # not used if set to null
ssl_ckpt_path: "ckpt/epoch=79-step=77840.ckpt" #"ckpt/BIG_epoch=99-step=97300.ckpt"

# logging options:
log_dir: "runs"
experiment_name: "cls_wesad"
experiment_version: null